config/routes.rb
Rails.application.routes.draw do

  namespace :diagnostician do
    resources :bookings, only: [ :index, :show, :new, :create, :update, :destroy] do
      member do
        get 'add_comment'
        get 'delete_comment'
      end
    end
    resources :diagnostics, only: [ :index, :show, :new, :create, :edit] do
      member do
        get 'add_plan'
        get 'delete_plan'
      end
    end
    resources :users, only: [:show, :index]
    resources :housings, only: [:index, :new, :create]
  end


  devise_for :users

  root to: 'pages#home'
  get '/eligibility', to: 'pages#eligibility'
  get '/diagnostician/valuations', to: 'diagnostician/housings#valuations'

  #inscription
  get '/disponibility', to: 'inscriptions#disponibility'
  get '/checkpoint', to: 'inscriptions#checkpoint'
  get '/confirmation', to: 'inscriptions#confirmation'

  resources :users, only: [:show]
  resources :answers
  resources :housings, only: [:index, :new, :create]
end

app/models/diagnostic.rb
class Diagnostic < ApplicationRecord
  has_one :booking
  has_one :user, through: :booking
  has_one :diagnostician, through: :booking, class_name: "User", foreign_key: "user_id"
  has_many :answers

  def booker
    self.booking.housing.users.first
  end

end

app/controllers/diagnostician/bookings_controller.rb
class Diagnostician::BookingsController < ApplicationController
  before_action :params_booking, only: [:show, :destroy, :update, :add_comment, :delete_comment]

  def index
    @bookings = policy_scope(Booking).where(diagnostician: current_user)
    authorize @bookings
    @dates = @bookings.map{ |booking| booking.set_at}
    @user = User.find_by_first_name("Jo") # TEMPORARY - There is only one diagnostician
    authorize @bookings
  end

  def show
    authorize @booking
    @housing = @booking.housing
    @markersPosition = [[@housing.latitude, @housing.longitude]]
  end

  def create
    diagnostician = User.find_by_first_name("Jo")

    authorize diagnostician

    if current_user.diagnostician?
      booking = diagnostician.bookings.new(booking_params)
      authorize booking
      booking.diagnostic = Diagnostic.new
      booking.housing = Housing.first # TEMPORARY - There is only one diagnostician, it housing needed in order to selfbook him
      if booking.save
        redirect_to diagnostician_bookings_path
      else
        (flash[:alert] = t('commons.issue'))
      end
    else
      @housing = Housing.create!(geoloc: session[:geoloc], latitude: session[:lat], longitude: session[:lng])
      @user_housing = UserHousing.create!(user: current_user, housing: @housing, user_state: 1)
      @diagnostic = Diagnostic.create!
      authorize @diagnostic
      date = session[:date]
      hour = session[:hour]
      @booking = Booking.new(user: diagnostician,
                            housing: @housing,
                            diagnostic: @diagnostic,
                            set_at: DateTime.parse(date.to_s + " 0"+ hour + ":00:00 +0000"),
                            comment:"Booking eligible n°#{Booking.count}",
                            confirmed_at: nil)
      authorize @booking
      if @housing.save! && @user_housing.save! && @diagnostic.save! && @booking.save!
        redirect_to user_path(current_user)
        flash[:notice] = t('inscription.confirmation')
      else
        redirect_to confirmation_path
        flash[:alert] = t('commons.issue')

      end
    end
  end

  def destroy
    authorize @booking
    if @booking.booker.diagnostician?
      location = diagnostician_bookings_path
    else
      location = diagnostician_users_path
    end
    @booking.destroy
    redirect_to location
  end

  def update
    authorize @booking
    @booking.update( confirmed_at: @booking.confirmed_at ? nil : DateTime.now )
    authorize @booking
    redirect_back(fallback_location: root_path)
  end

  def add_comment
    authorize @booking
    @booking.comment = params[:query][:comment]
    @booking.save!
    redirect_back(fallback_location: root_path)
  end

  def delete_comment
    authorize @booking
    @booking.comment = nil
    @booking.save!
    redirect_back(fallback_location: root_path)
  end

  private

  def params_booking
    @booking = Booking.find(params[:id])
    @user = current_user
  end

  def booking_params
    params.require(:booking).permit(:set_at, :comment, :id)
  end


end

app/controllers/diagnostician/diagnostics_controller.rb
class Diagnostician::DiagnosticsController < ApplicationController
  before_action :params_user, only: [:index, :show, :edit]
  before_action :params_diagnostic, only: [:show, :edit, :add_plan, :delete_plan]

  def index
    @diagnostics = policy_scope(Diagnostic)
    @diagnostics = @user.diagnostics # car un seul diagnosticien pour l'instant
    @housings = Housing.all
  end

  def show
    @sections = Section.all
    authorize @diagnostic
    @booking = @diagnostic.booking
    @markersPosition = [[@booking.housing.latitude, @booking.housing.longitude]]
    draw_marker(@booking.housing)
    if params[:query]
      @plan_id = params[:query][:address]
    end
  end

  def edit
    authorize @diagnostic
    @booking = @diagnostic.booking
    draw_marker(@booking.housing)
    @sections = Section.all
  end

  def add_plan
    authorize @diagnostic
    @diagnostic.plan = params[:query][:address]
    @diagnostic.save!
    redirect_to diagnostician_diagnostic_path(@diagnostic)
  end

  def delete_plan
    authorize @diagnostic
    @diagnostic.plan = nil
    @diagnostic.save!
    redirect_to diagnostician_diagnostic_path(@diagnostic)
  end

  private

  def params_user
    @user = current_user
  end

  def params_diagnostic
    @diagnostic = Diagnostic.find(params[:id])
  end
end

app/controllers/diagnostician/housings_controller.rb
class Diagnostician::HousingsController < ApplicationController
  def new
    @housing = policy_scope(Housing).new
    authorize @housing
  end

  def create
    policy_scope(Housing)
    @housing = Housing.new(housing_params)
    authorize @housing
    if @housing.save
      session[:geoloc] = @housing.geoloc
      session[:floor] = @housing.floor
      session[:rooms] = @housing.rooms
      session[:surface] = @housing.surface
      session[:construction_quality] = @housing.construction_quality
      session[:bathroom_quality] = @housing.bathroom_quality
      session[:living_quality] = @housing.living_quality
      session[:rooms_quality] = @housing.rooms_quality
      session[:parking_lot] = @housing.parking_lot
      session[:basement] = @housing.basement
      session[:elevator] = @housing.elevator
      session[:concierge] = @housing.concierge
      session[:collective_heating] = @housing.collective_heating
      session[:balcony] = @housing.balcony
      # redirect_to new_diagnostician_housing_path
    end

    if minimum_for_valuation
      url_queue = []
      params[:housing].each do |value|
        url_queue << "&#{value}=#{params[:housing][value]}"
      end

      url = "https://bdvapis.appspot.com/#{ENV['BDV_API_KEY']}/valuation/v1.0.0/purchase?#{url_queue.join[1..-1]}"

      header = {'origin': "http://diag-o.herokuapp.com"}

      body = begin
        RestClient.get(url, headers = header)
      rescue => e
        e.response.body
      end

      response = JSON.parse(body)

      if e && JSON.parse(e.response.body)["status"]
        @error = "Error:" + JSON.parse(e.response.body)["message"]
      else
        @price = response["results"]["valuation"]["asset_standard_price"].to_i.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1 ').reverse
      end

      redirect_to new_diagnostician_housing_path
    else
      flash[:notice] = t('valuation.form_rescue')
    end
  end

  def update
  end

  def delete
  end

  def index
    policy_scope(Housing)
    @housings = Housing.all.select{ |housing| housing.bookings.presence && housing.geoloc != "Diagnostician house" }
  end

  def valuations
    policy_scope(Housing)
    housings = Housing.where(only_valuation: true)
    authorize housings
    @housings = housings.reverse
  end

  private

  def minimum_for_valuation
    params[:housing][:geoloc] && params[:housing][:surface] && params[:housing][:floor]
  end

  def housing_params
    params.require(:housing).permit(:geoloc,
                                    :floor,
                                    :rooms,
                                    :surface,
                                    :construction_quality,
                                    :kitchen_quality,
                                    :bathroom_quality,
                                    :living_quality,
                                    :rooms_quality,
                                    :parking_lot,
                                    :basement,
                                    :elevator,
                                    :concierge,
                                    :balcony,
                                    :collective_heating,
                                    :valuation,
                                    :only_valuation,
                                     )
  end
end

app/controllers/diagnostician/users_controller.rb
class Diagnostician::UsersController < ApplicationController
  def index
    @user = current_user
    policy_scope(Booking)
    @bookings = decreasing_date(@user.private_bookings)
  end
end

app/views/diagnostician/diagnostics/_ask_and_display.html.erb
<div id="tab-plan" class="card-note card-line text-center tabcontent">
  <% if @diagnostic.plan.nil? %>
    <h4>Ajouter un plan FloorPlanner:</h4>
    <%= render "shared/search_form", url: add_plan_path, method_name: 'get', placeholder: t('diagnostic.placeholder'), label: false, btn_text: t('diagnostic.button_text') %>
  <% else %>
    <h4>Plans:
    <%= link_to delete_plan_path, method: :get do %>
      <i class="fa fa-trash"></i> (Retirer ce plan)
    <% end %>
   </h4>
    <div id='app'>
        <div id='fp2d'>
          <iframe
            src="https://floorplanner.com/projects/<%= @diagnostic.plan %>/viewer?view=2d&section=180"
            frameborder='0'
            width='100%'
            height='650'
            scrolling='no'
            zoom='1'
            >
          </iframe>
        </div>
        <div id='fp3d'></div>
    </div>
  <% end %>
</div>

app/views/diagnostician/diagnostics/_ask_and_display_plan.html.erb
<div id="tab-plan" class="card-note card-line text-center tabcontent">
  <% if @diagnostic.plan.nil? %>
    <h4>Ajouter un plan FloorPlanner:</h4>
    <%= render "shared/search_form", url: add_plan_diagnostician_diagnostic_path(@diagnostic), method_name: 'get', placeholder: t('diagnostic.placeholder'), label: false, btn_text: t('diagnostic.button_text') %>
  <% else %>
    <h3>Plans:
    <%= link_to delete_plan_diagnostician_diagnostic_path(@diagnostic), method: :get do %>
      <i class="fa fa-trash"></i> (Retirer ce plan)
    <% end %>
   </h3>
   <%= render "display_plan" %>
  <% end %>
</div>

app/views/diagnostician/diagnostics/_display_plan.html.erb
<div id='app'>
  <div id='fp2d'>
    <iframe
      src="https://floorplanner.com/projects/<%= @diagnostic.plan %>/viewer?view=2d&section=180"
      frameborder='0'
      width='100%'
      height='650'
      scrolling='no'
      zoom='1'
      >
    </iframe>
  </div>
  <div id='fp3d'></div>
</div>

app/views/diagnostician/diagnostics/edit.html.erb
<div class="dashboard-wrap">
  <%= render "shared/sidebar"%>
  <%= render "shared/sidebar_forjs"%>

  <div class="dashboard-content with_right_sidebar">
    <div class="padding-box">
      <h1 class="text-center">Diagnostique <%= @diagnostic.id %>
        <%= link_to(content_tag(:i, nil, class: 'fa fa-eye'), diagnostician_diagnostic_path(@diagnostic))%>
      </h1>

      <!-- INFOS -->
      <div class="tabcontent" id="tab-info">
        <%= render "shared/card_line" %>
        <div class="card-note card-line text-center">
          <%= render "shared/map"%>
        </div>
      </div>

      <!-- PLAN -->
      <% if @user.diagnostician? %>
        <%= render "ask_and_display_plan" %>
      <% end %>

      <!-- FORM -->
      <% @sections.each do |section| %>
        <div id="Section-<%= section.id %>" class="tabcontent card-note card-line text-center">
          <h3 class="margin-bottom-medium"><%= section.name.capitalize %></h3>
            <% section.questions.each do |q| %>
              <div class="margin-bottom-small text-left">
                <%= simple_form_for q.answers.find_or_create_by(diagnostic: @diagnostic) do |f| %>
                  <%= f.input q.input_type.to_sym, { label: q.name }.merge( q.option_choice_id? ? {collection: q.option_choices} : {}) %>
                <% end %>
              </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(window).load(function(){
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
      }
      document.getElementById('tab-info').style.display = "block";
      document.getElementById('tab-btn-info').className += " active";
    });
  <% end %>
<% end %>

<script>
 function openTab(event, elementId) {
  // Declare all variables
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
  }

  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(elementId).style.display = "block";
  event.currentTarget.className += " active";
  }

   // Get the element with id="defaultOpen" and click on it
  document.getElementById("Section1").click();

</script>

app/views/diagnostician/diagnostics/index.html.erb
<div class="dashboard-wrap">
  <%= render "shared/sidebar"%>

  <div class="dashboard-content">
    <div class="padding-box">
      <h3 class="text-center">Mes diagnostics</h3>
      <%= render "shared/diagnostics_list" %>
    </div>
  </div>
</div>

app/views/diagnostician/diagnostics/show.html.erb
<div class="dashboard-wrap">
  <%= render "shared/sidebar"%>
  <%= render "shared/sidebar_forjs"%>

  <div class="dashboard-content with_right_sidebar">
    <div class="padding-box">
      <h1 class="text-center">Diagnostique <%= @diagnostic.id %>
        <% if @user.diagnostician? %>
          <%= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_diagnostician_diagnostic_path(@diagnostic))%>
        <% end %>
      </h1>

      <!-- INFOS -->
      <div class="tabcontent" id="tab-info">
        <%= render "shared/card_line" %>
        <div class="card-note card-line text-center">
          <%= render "shared/map"%>
        </div>
      </div>

      <!-- PLAN -->
      <% if @user.diagnostician? %>
        <%= render "ask_and_display_plan" %>
      <% end %>

      <!-- FORM -->
      <% @sections.each do |section| %>
        <div id="Section-<%= section.id %>" class="tabcontent card-note card-line text-center">
          <h3 class="underline"><%= t('sections.'+section.name).capitalize %></h3>
          <% section.questions.each do |q| %>
            <div class="text-left">
              <p><%= q.name %></p>
              <% if q.answers.nil? %>
                <p>-------</p>
              <% else %>
                <p>-------</p>
                <%#= q.answer_is(@diagnostic).litteral_answer %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<!-- JS FOR PLAN -->
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(window).load(function(){
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
      }
      document.getElementById('tab-info').style.display = "block";
      document.getElementById('tab-btn-info').className += " active";
    });

    var theme = {
      ui: {
        initView: '2d',
        rotate3d: false,
        zoom: '1'
      },
      engine: {
        useSection3D: false,
        wallSectionHeight: 180,
        wallTopColor3D: "7F7F7F",
        wallTopColor2D: "000000",
        engineAutoDims: true,
        showGrid: false,
        showDims: true,
        showObjects: true,
        showLabels: true,
        useMetric: true,
        visuals: 'ALL',
      }
    };
  <% end %>
<% end %>

<script>
 function openTab(event, elementId) {
  // Declare all variables
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
  }

  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(elementId).style.display = "block";
  event.currentTarget.className += " active";

    // Get the element with id="defaultOpen" and click on it
  // document.getElementById("tab-info").click(); << INFINITE LOOP?
  }


</script>