config/routes.rb
Rails.application.routes.draw do

  namespace :diagnostician do
    resources :bookings, only: [ :index, :show, :new, :create, :update, :destroy] do
      member do
        get 'add_comment'
        get 'delete_comment'
      end
    end
    resources :diagnostics, only: [ :index, :show, :new, :create, :edit] do
      member do
        get 'add_plan'
        get 'delete_plan'
      end
    end
    resources :users, only: [:show, :index]
    resources :housings, only: [:index, :new, :create]
  end


  devise_for :users

  root to: 'pages#home'
  get '/eligibility', to: 'pages#eligibility'
  get '/diagnostician/valuations', to: 'diagnostician/housings#valuations'

  #inscription
  get '/disponibility', to: 'inscriptions#disponibility'
  get '/checkpoint', to: 'inscriptions#checkpoint'
  get '/confirmation', to: 'inscriptions#confirmation'

  resources :users, only: [:show]
  resources :answers
  resources :housings, only: [:index, :new, :create]
end

app/views/shared/_breadcrumb.html.erb
<div class="breadcrumb flex-horizontal">
  <ul>
    <% 3.times do |x| %>
      <li class="<%= "green" if session[:page] >= x+1 %>">
        <p class="number-in-circle"><%= x+1 %></p>
        <p class="text-over-line"><%= t('inscription.breadcrumb'+(x+1).to_s) %></p>
        <div class="line-under-text"></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_button_with_data.html.erb
  <%= simple_form_for :booking, url: diagnostician_bookings_path, method: :post do |f| %>
    <%= f.input :set_at, input_html: { value: set_at }, as: :hidden %>
    <%= f.button :submit, value: (set_at.hour == 8 ? "8h-12h" : "14h-18h"), data: { disable_with: "-" }, class: btn_class %>
  <% end %>

app/views/shared/_calendar.html.erb
<%= month_calendar do |date| %>
  <div class="date-day"><%= date.day %></div>
  <div class="cell-content">
    <div class="btn-container">

      <% ["8","14"].each do |hour| %>
        <!-- PAST -->
        <% unless date_in_futur(date) %>
          <% if @dates.include? date_with_hour(date, hour) %>
            <%= link_to diagnostician_booking_path(this_booking(@dates, date, hour)) do %>
              <div class= "btn btn-calendar btn-calendar-booked"><i class="fa fa-eye"></i></div>
            <% end %>
          <% end %>
        <!-- FUTUR -->
        <% else %>
          <% unless @dates.include? date_with_hour(date, hour) %>
            <%= render "shared/button_with_data", set_at: date_with_hour(date, hour), btn_class: "btn-calendar btn-calendar-tobook" %>
          <% else %>
            <% if this_booking(@dates, date, hour).booker == current_user %>
              <%= link_to diagnostician_booking_path(this_booking(@dates, date, hour)), method: :delete do %>
                <div class= "btn btn-calendar btn-calendar-booked">
                  <i class="fa fa-retweet"></i><p><%= t('booking.selfbook') %></p>
                </div>
              <% end %>
            <% else %>
              <%= link_to diagnostician_booking_path(this_booking(@dates, date, hour)) do %>
                <div class= "btn btn-calendar btn-calendar-booked">
                  <i class="fa fa-eye"></i>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_card_line.html.erb
<div class="card-note card-line text-center">
  <h3><%= @booking.booker.first_name.capitalize %> <%= @booking.booker.last_name.capitalize %></h3>
  <div class="flexbox">
    <div class="card-mini border-right"><i class="fa fa-envelope-o"></i><p><%= @booking.booker.email %></p></div>
    <div class="card-mini border-right"><i class="fa fa-phone"></i><p><%= @booking.booker.phone %></p></div>
    <div class="card-mini"><i class="fa fa-home"></i><p><%= @booking.housing.geoloc != "" ?  @booking.housing.geoloc : t('housing.no_address')  %></p></div>
  </div>
</div>

app/views/shared/_card_note.html.erb
<div class="card-note text-center">
  <div class="underline">
    <!-- <i class="fa fa-user big"></i> -->
    <h3><%= @booking.booker.first_name.capitalize %> <%= @booking.booker.last_name.capitalize %></h3>
    <div class="flexbox">
      <div class="card-mini border-right"><i class="fa fa-envelope-o"></i><p><%= @booking.booker.email %></p></div>
      <div class="card-mini"><i class="fa fa-phone"></i><p><%= @booking.booker.phone %></p></div>
    </div>
  </div>
  <div class="flexbox">
    <div class="card-mini"><i class="fa fa-home"></i><p><%= @booking.housing.geoloc %></p></div>
  </div>
  <div><p>Demande reçue le <%= @booking.created_at.strftime(" %d %b %Y") %></p></div>
  <% if @booking.confirmed_at.nil? != true && @booking.confirmed_at > @booking.created_at %>
    <p>Demande confirmée le <%= @booking.confirmed_at.strftime(" %d %b %Y") %></p>
  <% end %>
  <div class="btns">
    <%= link_to "Le rendez-vous est confirmé", "#", class: "btn-slim btn-anis flexbox margin-bottom-small" %>
    <%= link_to "Supprimer le rendez-vous", "#", class: "btn-slim btn-red flexbox" %>
  </div>
</div>

app/views/shared/_diagnostics_list.html.erb
<% @diagnostics.each do |diagnostic| %>
    <div class="list-element">
      <div class="line">
        <div class="user-name">
          <%= link_to diagnostician_diagnostic_path(diagnostic) do %>
            <h5>Diagnostic réf diag-o<%= diagnostic.id %></h5>
          <% end %>
        </div>
        <div class="user-status">
          <h5>Rendez-vous du <%= diagnostic.booking.set_at.strftime("%d %b %Y") %></h5>
        </div>
      </div>
      <div class="line">
        <div>
          <p class="user-data address">
            <%= diagnostic.booking.booker.first_name %> <%= diagnostic.booking.booker.last_name %> : <%= diagnostic.booking.housing.geoloc %>
          </p>
        </div>
        <div class="min-width text-right">
          <p class="status declined"><%= t('diagnostic.pending') %>
            <%= link_to diagnostician_diagnostic_path(diagnostic) do %>
              <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="Voir le diagnostic"></i>
            <% end %>


            <% if @user.diagnostician? %>
              <%= link_to edit_diagnostician_diagnostic_path(diagnostic) do%>
                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Modifier le diagnostic"></i>
              <% end %>
            <% end %>

          </p>
        </div>
      </div>
    </div>
<% end %>

<% content_for (:after_js) do %>
  <script>
    $(function () {
    $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fixed-under-top" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fixed-under-top" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_map.html.erb
<div id="map"></div>

<%= content_for :after_js do %>
  <script>
    var markersPositionArray = <%= @markersPosition %>;

    function initBookinsMap() {

      var markersPositions = [];
      for(i=0; i<markersPositionArray.length; i++){
        markersPositions.push({ lat:markersPositionArray[i][0], lng:markersPositionArray[i][1] });
      }
      var zoneMarqueurs = new google.maps.LatLngBounds();
      var optionsCarte = {
        zoom: 16,
        center: markersPositions[0]
      }
      var myMap = new google.maps.Map( document.getElementById("map"), optionsCarte );
      markersPositions.forEach( function(latlng) {
        var latitude = latlng.lat,
          longitude = latlng.lng;
        var optionsMarqueur = {
          map: myMap,
          position: new google.maps.LatLng( latitude, longitude ),
          icon: "http://res.cloudinary.com/doodlid/image/upload/v1507545075/diago/diago_marker.svg"
        };
        var marqueur = new google.maps.Marker( optionsMarqueur );
        zoneMarqueurs.extend( marqueur.getPosition() );
      } );
      if (<%= @private_bookings.present? ? @private_bookings.size : 0 %> > 1) {
        myMap.fitBounds( zoneMarqueurs );
      }
    }

    initBookinsMap();

  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon" id="page0">
  <%= link_to root_path, class: "navbar-wagon-brand", id:"logo" do %>
    <%= image_tag "diag-o-logo_small.png" %>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <% if current_user.diagnostician? %>
        <%= link_to "+ Ajouter un nouveau diagnostique", "#", class: "btn-slim flexbox" %>
        <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-bell"></i>
        <% end %>
      <% end %>

      <%= link_to t(".profile", default: "profil"), user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_out", default: "déconnexion"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
      <%= link_to t(".sign_in", default: "Le risque inondation"), "#page2", class: "navbar-wagon-item navbar-wagon-link scroll" %>
      <%= link_to t(".sign_in", default: "Espace pro"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_next_page.html.erb
<%= link_to(content_tag(:i, nil, class: "fa fa-#{icon}"), target_page, class: "next_page scroll") %>

app/views/shared/_search_form.html.erb
<div class="form-fake-wrap flex-vertical">
  <%= simple_form_for :query, url: url , method: :get do |f| %>
      <%= f.input :address, label: false, placeholder: placeholder %>
      <%= f.button :submit, class: 'btn btn-green', id: "button-search", data: { disable_with: "recherche..." }, value: btn_text %>
  <% end %>
</div>

app/views/shared/_sidebar_forjs.html.erb
<div class="sidebar-right">
  <button class="sidebar-button-capsule tablinks" onclick="openTab(event, 'tab-info')" id="tab-btn-info"><%= t('sections.infos').capitalize %></button>
  <button class="sidebar-button-capsule tablinks" onclick="openTab(event, 'tab-plan')" id="tab-btn-plan"><%= t('sections.plans').capitalize %></button>

  <% @sections.each do |section| %>
    <button class="sidebar-button-capsule tablinks" onclick="openTab(event, 'Section-<%= section.id %>')" id="Section<%= section.id %>"><%= t('sections.'+section.name).capitalize %>
    </button>
  <% end %>
</div>

app/views/shared/_tabs.html.erb
<div class="tabs">
  <div class="tab tab-border long-tab <%= "tab-active-bg" if current_page?(link1) %>">
    <p><%= link_to t('housing.valuation_new'), link1 %></p>
  </div>
  <div class="tab tab-border long-tab <%= "tab-active-bg" if current_page?(link2) %>">
    <p><%= link_to t('housing.valuation_index'), link2 %></p>
  </div>
  <div class="tab tab-border long-tab <%= "tab-active-bg" if current_page?(link3) %>">
    <p><%= link_to t('housing.housings'), link3 %></p>
  </div>
</div>

app/views/shared/_textarea_form.html.erb
<%= simple_form_for :query, url: url , method: :get do |f| %>
  <div class="form-fake-wrap flex-vertical">
    <%= f.input :comment, label: false, id: "textarea", as: :text, :input_html => { :cols => 5, :rows => 10, value: text, :resize => "none" } %>
  </div>
    <%= f.button :submit, class: 'btn btn-green', value: btn_text %>
<% end %>