config/routes.rb
Rails.application.routes.draw do

  namespace :diagnostician do
    resources :bookings, only: [ :index, :show, :new, :create, :update, :destroy] do
      member do
        get 'add_comment'
        get 'delete_comment'
      end
    end
    resources :diagnostics, only: [ :index, :show, :new, :create, :edit] do
      member do
        get 'add_plan'
        get 'delete_plan'
      end
    end
    resources :users, only: [:show, :index]
    resources :housings, only: [:index, :new, :create]
  end


  devise_for :users

  root to: 'pages#home'
  get '/eligibility', to: 'pages#eligibility'
  get '/diagnostician/valuations', to: 'diagnostician/housings#valuations'

  #inscription
  get '/disponibility', to: 'inscriptions#disponibility'
  get '/checkpoint', to: 'inscriptions#checkpoint'
  get '/confirmation', to: 'inscriptions#confirmation'

  resources :users, only: [:show]
  resources :answers
  resources :housings, only: [:index, :new, :create]
end

app/models/housing.rb
class Housing < ApplicationRecord
  has_many :bookings
  has_many :user_housings
  has_many :users, through: :user_housings

  delegate :diagnostician, to: :bookings, allow_nil: true

  # validates :floor, presence: true
  # validates :surface, presence: true
  # validates :rooms, presence: true

  def location
    self.latitude.presence
  end
end

app/controllers/diagnostician/bookings_controller.rb
class Diagnostician::BookingsController < ApplicationController
  before_action :params_booking, only: [:show, :destroy, :update, :add_comment, :delete_comment]

  def index
    @bookings = policy_scope(Booking).where(diagnostician: current_user)
    authorize @bookings
    @dates = @bookings.map{ |booking| booking.set_at}
    @user = User.find_by_first_name("Jo") # TEMPORARY - There is only one diagnostician
    authorize @bookings
  end

  def show
    authorize @booking
    @housing = @booking.housing
    @markersPosition = [[@housing.latitude, @housing.longitude]]
  end

  def create
    diagnostician = User.find_by_first_name("Jo")

    authorize diagnostician

    if current_user.diagnostician?
      booking = diagnostician.bookings.new(booking_params)
      authorize booking
      booking.diagnostic = Diagnostic.new
      booking.housing = Housing.first # TEMPORARY - There is only one diagnostician, it housing needed in order to selfbook him
      if booking.save
        redirect_to diagnostician_bookings_path
      else
        (flash[:alert] = t('commons.issue'))
      end
    else
      @housing = Housing.create!(geoloc: session[:geoloc], latitude: session[:lat], longitude: session[:lng])
      @user_housing = UserHousing.create!(user: current_user, housing: @housing, user_state: 1)
      @diagnostic = Diagnostic.create!
      authorize @diagnostic
      date = session[:date]
      hour = session[:hour]
      @booking = Booking.new(user: diagnostician,
                            housing: @housing,
                            diagnostic: @diagnostic,
                            set_at: DateTime.parse(date.to_s + " 0"+ hour + ":00:00 +0000"),
                            comment:"Booking eligible n°#{Booking.count}",
                            confirmed_at: nil)
      authorize @booking
      if @housing.save! && @user_housing.save! && @diagnostic.save! && @booking.save!
        redirect_to user_path(current_user)
        flash[:notice] = t('inscription.confirmation')
      else
        redirect_to confirmation_path
        flash[:alert] = t('commons.issue')

      end
    end
  end

  def destroy
    authorize @booking
    if @booking.booker.diagnostician?
      location = diagnostician_bookings_path
    else
      location = diagnostician_users_path
    end
    @booking.destroy
    redirect_to location
  end

  def update
    authorize @booking
    @booking.update( confirmed_at: @booking.confirmed_at ? nil : DateTime.now )
    authorize @booking
    redirect_back(fallback_location: root_path)
  end

  def add_comment
    authorize @booking
    @booking.comment = params[:query][:comment]
    @booking.save!
    redirect_back(fallback_location: root_path)
  end

  def delete_comment
    authorize @booking
    @booking.comment = nil
    @booking.save!
    redirect_back(fallback_location: root_path)
  end

  private

  def params_booking
    @booking = Booking.find(params[:id])
    @user = current_user
  end

  def booking_params
    params.require(:booking).permit(:set_at, :comment, :id)
  end


end

app/controllers/diagnostician/diagnostics_controller.rb
class Diagnostician::DiagnosticsController < ApplicationController
  before_action :params_user, only: [:index, :show, :edit]
  before_action :params_diagnostic, only: [:show, :edit, :add_plan, :delete_plan]

  def index
    @diagnostics = policy_scope(Diagnostic)
    @diagnostics = @user.diagnostics # car un seul diagnosticien pour l'instant
    @housings = Housing.all
  end

  def show
    @sections = Section.all
    authorize @diagnostic
    @booking = @diagnostic.booking
    @markersPosition = [[@booking.housing.latitude, @booking.housing.longitude]]
    draw_marker(@booking.housing)
    if params[:query]
      @plan_id = params[:query][:address]
    end
  end

  def edit
    authorize @diagnostic
    @booking = @diagnostic.booking
    draw_marker(@booking.housing)
    @sections = Section.all
  end

  def add_plan
    authorize @diagnostic
    @diagnostic.plan = params[:query][:address]
    @diagnostic.save!
    redirect_to diagnostician_diagnostic_path(@diagnostic)
  end

  def delete_plan
    authorize @diagnostic
    @diagnostic.plan = nil
    @diagnostic.save!
    redirect_to diagnostician_diagnostic_path(@diagnostic)
  end

  private

  def params_user
    @user = current_user
  end

  def params_diagnostic
    @diagnostic = Diagnostic.find(params[:id])
  end
end

app/controllers/diagnostician/housings_controller.rb
class Diagnostician::HousingsController < ApplicationController
  def new
    @housing = policy_scope(Housing).new
    authorize @housing
  end

  def create
    policy_scope(Housing)
    @housing = Housing.new(housing_params)
    authorize @housing
    if @housing.save
      session[:geoloc] = @housing.geoloc
      session[:floor] = @housing.floor
      session[:rooms] = @housing.rooms
      session[:surface] = @housing.surface
      session[:construction_quality] = @housing.construction_quality
      session[:bathroom_quality] = @housing.bathroom_quality
      session[:living_quality] = @housing.living_quality
      session[:rooms_quality] = @housing.rooms_quality
      session[:parking_lot] = @housing.parking_lot
      session[:basement] = @housing.basement
      session[:elevator] = @housing.elevator
      session[:concierge] = @housing.concierge
      session[:collective_heating] = @housing.collective_heating
      session[:balcony] = @housing.balcony
      # redirect_to new_diagnostician_housing_path
    end

    if minimum_for_valuation
      url_queue = []
      params[:housing].each do |value|
        url_queue << "&#{value}=#{params[:housing][value]}"
      end

      url = "https://bdvapis.appspot.com/#{ENV['BDV_API_KEY']}/valuation/v1.0.0/purchase?#{url_queue.join[1..-1]}"

      header = {'origin': "http://diag-o.herokuapp.com"}

      body = begin
        RestClient.get(url, headers = header)
      rescue => e
        e.response.body
      end

      response = JSON.parse(body)

      if e && JSON.parse(e.response.body)["status"]
        @error = "Error:" + JSON.parse(e.response.body)["message"]
      else
        @price = response["results"]["valuation"]["asset_standard_price"].to_i.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1 ').reverse
      end

      redirect_to new_diagnostician_housing_path
    else
      flash[:notice] = t('valuation.form_rescue')
    end
  end

  def update
  end

  def delete
  end

  def index
    policy_scope(Housing)
    @housings = Housing.all.select{ |housing| housing.bookings.presence && housing.geoloc != "Diagnostician house" }
  end

  def valuations
    policy_scope(Housing)
    housings = Housing.where(only_valuation: true)
    authorize housings
    @housings = housings.reverse
  end

  private

  def minimum_for_valuation
    params[:housing][:geoloc] && params[:housing][:surface] && params[:housing][:floor]
  end

  def housing_params
    params.require(:housing).permit(:geoloc,
                                    :floor,
                                    :rooms,
                                    :surface,
                                    :construction_quality,
                                    :kitchen_quality,
                                    :bathroom_quality,
                                    :living_quality,
                                    :rooms_quality,
                                    :parking_lot,
                                    :basement,
                                    :elevator,
                                    :concierge,
                                    :balcony,
                                    :collective_heating,
                                    :valuation,
                                    :only_valuation,
                                     )
  end
end

app/controllers/diagnostician/users_controller.rb
class Diagnostician::UsersController < ApplicationController
  def index
    @user = current_user
    policy_scope(Booking)
    @bookings = decreasing_date(@user.private_bookings)
  end
end

app/views/diagnostician/housings/create.html.erb
<h1>Housings#create</h1>
<p>Find me in app/views/housings/create.html.erb</p>

app/views/diagnostician/housings/delete.html.erb
<h1>Housings#delete</h1>
<p>Find me in app/views/housings/delete.html.erb</p>

app/views/diagnostician/housings/index.html.erb
<div class="dashboard-wrap">
  <%= render "/shared/sidebar"%>
  <div class="dashboard-content">
    <%= render "shared/tabs", link1: new_diagnostician_housing_path, link2: diagnostician_valuations_path, link3: diagnostician_housings_path %>
    <div class="padding-box">
      <h3 class="text-center">Domiciliations :</h3>

      <% @housings.each do |housing| %>
        <div class="list-element">
          <div class="line">
            <h5>Adresse : <%= housing.geoloc %></h5>
          </div>
          <div class="line">
            <h5>Évaluation : <%= housing.valuation %></h5>
          </div>
          <div class="line">
            <div class="list-name">
              <strong><p>Données principales :</p></strong>
              <p>Étage(s) : <%= housing.floor %></p>
              <p>Pièce(s) : <%= housing.rooms %></p>
              <p>Surface : <%= housing.surface %></p>
            </div>
            <div class="list-name">
              <strong><p>Qualité :</p></strong>
              <p>Batiment : <%= housing.construction_quality %></p>
              <p>Cuisine : <%= housing.kitchen_quality %></p>
              <p>Salle de bain : <%= housing.bathroom_quality %></p>
              <p>Salon : <%= housing.living_quality %></p>
              <p>Chambres : <%= housing.rooms_quality %></p>
            </div>
            <div class="list-name">
              <strong><p>Commodité : </p></strong>
              <p>Parking : <%= housing.parking_lot %></p>
              <p>Cave : <%= housing.basement %></p>
              <p>Concierge : <%= housing.concierge %></p>
              <p>Ascenseur : <%= housing.elevator %></p>
              <p>Balcon : <%= housing.balcony %></p>
              <p>Chauffage collectif : <%= housing.collective_heating %></p>
            </div>
            </div>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/diagnostician/housings/new.html.erb
<div class="dashboard-wrap">
  <%= render "shared/sidebar" %>

  <div class="dashboard-content">
    <%= render "shared/tabs", link1: new_diagnostician_housing_path, link2: diagnostician_valuations_path, link3: diagnostician_housings_path %>
    <div class="padding-box">

        <div class="flex-horizontal">
          <div class="form-box">
            <div class="form-title flexbox">
              <h3 class="text-center "><%= t('valuation.form_title') %></h3>
            </div>
            <% unless params[:query].nil? %>
              <% if @price.nil? && @error %>
                <div class="valuation-message form-title error flexbox relative">
                  <p class="text-center"><%= @error %></p>
                  <i class="fa fa-times close-it clickable"></i>
                </div>
              <% elsif @price %>
                <div class="valuation-message form-title ok flexbox relative">
                  <h3 class="text-center">Bien estimé à: <%= @price %>€</h3>
                  <i class="fa fa-times close-it clickable"></i>
                </div>
              <% end %>
            <% end %>
            <div class="form-inputs">
              <h4>Données du bien:</h4>
              <%= simple_form_for @housing, url: diagnostician_housings_path, method: :post do |f| %>
                <p>Les champs avec étoiles(*) sont obligatoires.</p>
                <%= f.input :geoloc, input_html: {value: session[:address] || "" }, label: t('housing.field.geoloc') %>
                <%= f.input :floor, collection: 0..60, placeholder: "0", label: t('housing.field.floor'), error: 'Username is mandatory, please specify one' %>
                <%= f.input :surface, placeholder: '0', label: t('housing.field.surface') %>
                <%= f.input :rooms, collection: 1..15, placeholder: "0", label: t('housing.field.rooms') %>
                <%= f.input :construction_quality, collection: 0..5, label: t('housing.field.construction') %>
                <%= f.input :kitchen_quality, collection: 0..5, label: t('housing.field.kitchen') %>
                <%= f.input :bathroom_quality, collection: 0..5, label: t('housing.field.bathroom') %>
                <%= f.input :living_quality, collection: 0..5, label: t('housing.field.living') %>
                <%= f.input :rooms_quality, collection: 0..5, label: t('housing.field.room') %>
                <%= f.input_field :only_valuation, value: true, as: :hidden %>
                <div class="row">
                  <div class="col-xs-6 col-sm-6 col-md-12">
                    <%= f.input :parking_lot, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.parking') %>
                    <%= f.input :basement, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.basement') %>
                    <%= f.input :elevator, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.elevator'), class: "checkbox-inline" %>
                  </div>
                  <div class="col-xs-6 col-sm-6 col-md-12">
                    <%= f.input :concierge, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.concierge') %>
                    <%= f.input :collective_heating, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.heating') %>
                    <%= f.input :balcony, as: :boolean, checked_value: true, unchecked_value: false, label: t('housing.field.balcony') %>
                  </div>
                </div>
                <%= f.button :submit, class: 'btn-green', value: "Évaluer", id:"submit_valuation" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for (:after_js) do %>
  <script>
    var housingAddress = document.getElementById('housing_geoloc');

    function initAutoComplete() {
      var autocomplete = new google.maps.places.Autocomplete(housingAddress, { types: [ 'geocode' ] });
      google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      google.maps.event.addDomListener(housingAddress, 'keydown', function(e) {
        if (e.key === "Enter") {
          e.preventDefault(); // Do not submit the form on Enter.
        }
      });
    }

    function onPlaceChanged() {
      var place = this.getPlace();
      var components = getAddressComponents(place);
    }

    function getAddressComponents(place) {

      if (window.console && typeof console.log === "function") {

      }

      var street_number = null;
      var route = null;
      var zip_code = null;
      var city = null;
      var country_code = null;
      for (var i in place.address_components) {
        var component = place.address_components[i];
        for (var j in component.types) {
          var type = component.types[j];
          if (type === 'street_number') {
            street_number = component.long_name;
          } else if (type === 'route') {
            route = component.long_name;
          } else if (type === 'postal_code') {
            zip_code = component.long_name;
          } else if (type === 'locality') {
            city = component.long_name;
          } else if (type === 'postal_town' && city === null) {
            city = component.long_name;
          } else if (type === 'country') {
            country_code = component.short_name;
          }
        }
      }

      return {
        address: street_number === null ? route : (street_number + ' ' + route),
        zip_code: zip_code,
        city: city,
        country_code: country_code
      };
    }

    initAutoComplete();

    $(document).ready(function() {
      $('.close-it').click(function(){
        $('.valuation-message').remove();
      })
      var table = document.getElementById("new_housing");
      var fields = table.getElementsByTagName("input");
      for (var i = 0; i < fields.length; i++) {
        fields[i].addEventListener('keypress', function(event) {
          if (event.keyCode == 13) {
              event.preventDefault();
          }
        });
      }
    });
  </script>
<% end %>

app/views/diagnostician/housings/update.html.erb
<h1>Housings#update</h1>
<p>Find me in app/views/housings/update.html.erb</p>

app/views/diagnostician/housings/valuations.html.erb
<div class="dashboard-wrap">
  <%= render "/shared/sidebar"%>
  <div class="dashboard-content">
    <%= render "shared/tabs", link1: new_diagnostician_housing_path, link2: diagnostician_valuations_path, link3: diagnostician_housings_path %>
    <div class="padding-box">
      <h3 class="text-center">Domiciliations :</h3>

      <% @housings.each do |housing| %>
        <div class="list-element">
          <div class="line">
            <h5>Adresse : <%= housing.geoloc %></h5>
          </div>
          <div class="line">
            <h5>Évaluation : <%= housing.valuation %></h5>
          </div>
          <div class="line">
            <div class="list-name">
              <strong><p>Données principales :</p></strong>
              <p>Étage(s) : <%= housing.floor %></p>
              <p>Pièce(s) : <%= housing.rooms %></p>
              <p>Surface : <%= housing.surface %></p>
            </div>
            <div class="list-name">
              <strong><p>Qualité :</p></strong>
              <p>Batiment : <%= housing.construction_quality %></p>
              <p>Cuisine : <%= housing.kitchen_quality %></p>
              <p>Salle de bain : <%= housing.bathroom_quality %></p>
              <p>Salon : <%= housing.living_quality %></p>
              <p>Chambres : <%= housing.rooms_quality %></p>
            </div>
            <div class="list-name">
              <strong><p>Commodité : </p></strong>
              <p>Parking : <%= housing.parking_lot %></p>
              <p>Cave : <%= housing.basement %></p>
              <p>Concierge : <%= housing.concierge %></p>
              <p>Ascenseur : <%= housing.elevator %></p>
              <p>Balcon : <%= housing.balcony %></p>
              <p>Chauffage collectif : <%= housing.collective_heating %></p>
            </div>
            </div>
          </div>
      <% end %>

    </div>
  </div>
</div>